-- liquibase formatted sql

-- changeset Datical:1645116284286-1
CREATE TABLE "public"."contacts" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "firstname" VARCHAR(255), "lastname" VARCHAR(255), CONSTRAINT "contacts_pkey" PRIMARY KEY ("id"));