-- liquibase formatted sql

-- changeset Datical:1646347302236-1
CREATE TABLE "public"."actor" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Name" CHAR(1), "twitter" VARCHAR(15), CONSTRAINT "actor_pkey" PRIMARY KEY ("id"));

-- changeset Datical:1646347302236-2
CREATE TABLE "public"."colors" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "bcolor" VARCHAR, "fcolor" VARCHAR, CONSTRAINT "colors_pkey" PRIMARY KEY ("id"));

-- changeset Datical:1646347302236-3
CREATE TABLE "public"."contacts" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "firstname" VARCHAR(255), "lastname" VARCHAR(255), CONSTRAINT "contacts_pkey" PRIMARY KEY ("id"));

-- changeset Datical:1646347302236-4
DROP FUNCTION "public".bad_func;

-- changeset Datical:1646347302236-5
DROP TABLE "public"."bad_table";

